import type { AiSuggestionRequest } from '@/lib/ai/types';

/**
 * One payload builder, shared by both provider adapters *and* by the Settings
 * data-disclosure preview. That sharing is the point: the disclosure cannot
 * drift from what is actually sent, because it is generated by the same code.
 *
 * Data minimization is enforced here by construction — only the fields on
 * `AiSuggestionRequest` are ever rendered, and `note`/`amount` appear only when
 * the caller (the service, reading the stored opt-in toggles) put them on the
 * request. No date, account, balance, or transfer/payment/skip flag exists on
 * the request type at all, so none can reach a provider.
 */

/** Fixed, contains no user data. */
export const AI_SYSTEM_PROMPT = [
  'You categorize a single personal-finance transaction.',
  "You will be given a merchant/payee name, the transaction type, and the complete list of the user's existing categories.",
  'Choose the single best-fitting category from that list.',
  'You must pick from the list — never invent a category.',
  'If no category is a confident fit, return "none".',
  'Answer only by calling the provided tool.',
].join(' ');

/** The sentinel a model returns when nothing in the list is a confident fit. */
export const NO_MATCH_SENTINEL = 'none';

export const buildSuggestionPayload = (
  request: AiSuggestionRequest,
): { system: string; user: string; categoryIds: string[] } => {
  const lines: string[] = [`Payee: ${request.payee}`, `Type: ${request.type}`];
  if (request.note !== undefined) {
    lines.push(`Note: ${request.note}`);
  }
  if (request.amount !== undefined) {
    lines.push(`Amount: ${request.amount}`);
  }

  lines.push('');
  if (request.categories.length === 0) {
    lines.push('Categories: the user has no categories.');
  } else {
    lines.push('Categories (id<TAB>name):');
    for (const category of request.categories) {
      lines.push(`${category.id}\t${category.name}`);
    }
  }

  return {
    system: AI_SYSTEM_PROMPT,
    user: lines.join('\n'),
    // Order is the caller's responsibility (`orderBy: { name: 'asc' }`); this
    // builder never re-sorts. The `"none"` sentinel is appended one layer up,
    // by the adapter building its structured-output enum.
    categoryIds: request.categories.map((category) => category.id),
  };
};
